// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 7/6/2026, 9:22:24 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["/Users/mike/Desktop/r86/route-control-front/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/mike/Desktop/r86/route-control-front/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/mike/Desktop/r86/route-control-front/app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/mike/Desktop/r86/route-control-front/app/plugins/**/*.{js,ts,mjs}","/Users/mike/Desktop/r86/route-control-front/app/composables/**/*.{js,ts,mjs}","/Users/mike/Desktop/r86/route-control-front/app/utils/**/*.{js,ts,mjs}","/Users/mike/Desktop/r86/route-control-front/app/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/mike/Desktop/r86/route-control-front/app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/mike/Desktop/r86/route-control-front/app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/mike/Desktop/r86/route-control-front/app/app.config.{js,ts,mjs}","/Users/mike/Desktop/r86/route-control-front/app/spa-loading-template.html"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;